// <auto-generated />
namespace netmvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_userid_income : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_userid_income));
        
        string IMigrationMetadata.Id
        {
            get { return "202310270307486_Add_userid_income"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
