// <auto-generated />
namespace netmvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class proc_create_post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(proc_create_post));
        
        string IMigrationMetadata.Id
        {
            get { return "202310230713410_proc_create_post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
